server:
  port: 8088
  
spring:
  application:
    name: user-query-service
  r2dbc:
    url: r2dbc:h2:mem://./user-query-db
    username: user
    password:
  kafka:
    transferTopic: user_topics
    bootstrapServers: localhost:9092
    groupId: group-id
    maxAttempts: 1