server:
  port: 8087
  
spring:
  application:
    name: customer-command-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/customer

app:
  topic:
    audit: audit-topic
    user: user-topic