server:
  port: 8087
  
spring:
  application:
    name: user-command-service
  r2dbc:
    url: r2dbc:h2:mem://./user-write-db
    username: student
    password:
  kafka:
    transferTopic: user_topics
    bootstrapServers: localhost:9092
    groupId: group-id
    maxAttempts: 1