server:
  port: 8087
  
spring:
  application:
    name: user-command-service
  data:
    mongodb:
      uri: mongodb://localhost:27020/user
  kafka:
    transferTopic: user_topics
    bootstrapServers: localhost:9092
    groupId: group-id
    maxAttempts: 1