version: '3.8'
services:
  zookeeper:
    restart: unless-stopped
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    restart: unless-stopped
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper