version: '3.8'
services:
  audit-mongodb:
    image: mongo:4.4.15
    ports:
      - "127.0.0.1:27018:27017"
    # volumes:
    #   - ~/volumes/princely/store/mongodb/:/audit/db/

  gateway-mongodb:
        image: mongo:4.4.15
        ports:
          - "127.0.0.1:27019:27017"
        # volumes:
        #   - ~/volumes/princely/store/mongodb/:/gateway/db/

  user-command-mongodb:
    image: mongo:4.4.15
    ports:
      - "127.0.0.1:27020:27017"
    # volumes:
    #   - ~/volumes/princely/store/mongodb/:/user/db/

  user-query-mongodb:
    image: mongo:4.4.15
    ports:
      - "127.0.0.1:27021:27017"
    # volumes:
    #   - ~/volumes/princely/store/mongodb/:/user/db/

  zookeeper:
    restart: unless-stopped
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper