server:
  port: 8089
  
spring:
  application:
    name: audit-service
  r2dbc:
    url: r2dbc:h2:mem://./audit
    username: student
    password:
  kafka:
    transferTopic: user_topics
    bootstrapServers: localhost:9092
    groupId: group_id_2
    maxAttempts: 1