server:
  port: 8089
  
spring:
  application:
    name: audit-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/customer
  kafka:
    transferTopic: user_topics
    bootstrapServers: localhost:9092
    groupId: group-id
    maxAttempts: 1