server:
  port: 8090
    
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-command-service
        uri: lb://user-command-service
        predicates:
        - Path=/user/**
        - Method=POST,PUT,DELETE,PATCH
      - id: user-query-service
        uri: lb://user-query-service
        predicates:
        - Path=/user/**
        - Method=GET
      - id: audit-service
        uri: lb://audit-service
        predicates:
          - Path=/audit/**
          - Method=GET,POST,PUT,DELETE,PATCH